services:
  eventphotographer:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eventphotographer_db;Username=admin;Password=admin"
      ObjectStorage__ServiceURL: "http://minio:9000"
      ObjectStorage__ForcePathStyle: true
      ObjectStorage__AccessKey: admin
      ObjectStorage__Password: minioadmin123
      ObjectStorage__BucketName: event-photographer
    ports:
      - "8000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    profiles: 
      - web
  
  eventphotographer-worker:
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eventphotographer_db;Username=admin;Password=admin"
      ObjectStorage__ServiceURL: "http://minio:9000"
      ObjectStorage__ForcePathStyle: true
      ObjectStorage__AccessKey: admin
      ObjectStorage__Password: minioadmin123
      ObjectStorage__BucketName: event-photographer
    profiles: 
      - worker
   
  postgres:
    image: postgres:alpine 
    container_name: eventphotographer_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eventphotographer_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
    profiles: 
      - web
      - worker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 10

  pgweb:
    container_name: eventphotographer_pgweb
    restart: 'no'
    image: sosedoff/pgweb
    ports: 
      - "8008:8081" 
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/eventphotographer_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    profiles: 
      - web
      - worker

  minio: 
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"      # API port
      - "8009:9001"      # Console/Web UI port
    volumes:
      - ./storage_data:/data
    profiles: 
      - web
      - worker