services:
  eventphotographer:
    image: ${DOCKER_REGISTRY-}eventphotographer
    container_name: eventphotographer_app
    build:
      context: .
      dockerfile: EventPhotographer/Dockerfile

  eventphotographer-worker:
    image: ${DOCKER_REGISTRY-}eventphotographer-worker
    container_name: eventphotographer_worker
    build:
      context: .
      dockerfile: EventPhotographer.Worker/Dockerfile

  postgres:
    image: postgres:alpine 
    container_name: eventphotographer_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: eventphotographer_minio
    command: server /data --console-address ":9001"
