services:
  eventphotographer:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eventphotographer_db;Username=admin;Password=admin"
      ObjectStorage__ServiceURL: "http://minio:9000"
      ObjectStorage__ForcePathStyle: true
      ObjectStorage__AccessKey: admin
      ObjectStorage__Password: minioadmin123
      ObjectStorage__BucketName: event-photographer
      Sentry__Dsn: 
    ports:
      - "8000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    profiles: 
      - web
  
  eventphotographer-worker:
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=eventphotographer_db;Username=admin;Password=admin"
      ObjectStorage__ServiceURL: "http://minio:9000"
      ObjectStorage__ForcePathStyle: true
      ObjectStorage__AccessKey: admin
      ObjectStorage__Password: minioadmin123
      ObjectStorage__BucketName: event-photographer
      Sentry__Dsn: 
    profiles: 
      - worker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq: 
        condition: service_healthy
   
  postgres:
    image: postgres:alpine 
    container_name: eventphotographer_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eventphotographer_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
    profiles: 
      - web
      - worker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 1s
      retries: 10

  pgweb:
    container_name: eventphotographer_pgweb
    restart: 'no'
    image: sosedoff/pgweb
    ports: 
      - "8008:8081" 
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/eventphotographer_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    profiles: 
      - web
      - worker

  minio: 
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"      # API port
      - "8009:9001"      # Console/Web UI port
    volumes:
      - ./storage_data:/data
    profiles: 
      - web
      - worker

  # bugsink:
  #   container_name: eventphotographer_bugsink
  #   image: bugsink/bugsink:latest
  #   environment:
  #     SECRET_KEY: ")gi5x)k=)%ug4_iy5g1-t97&pzxwy$fi^k$-%mlyhme5h_n18R9Kl+GD2osxOHea2h$c)6Gf)f}oEZYVK,>M$aoxAwB|xPI.46Pjy.h;%xL:[M)"
  #     CREATE_SUPERUSER: "admin:admin"
  #     PORT: 8010
  #     DATABASE_PATH: "/data/bugsink.db"
  #     SINGLE_TEAM: True
  #     SINGLE_USER: True
  #   volumes: 
  #     - ./bugsink_data:/data
  #   ports: 
  #     - "8010:8010"
  #   profiles: 
  #     - web 
  #     - worker

  rabbitmq:
    container_name: eventphotographer_rabbitmq
    image: rabbitmq:4-management
    ports:
      - "8011:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 30s
      retries: 10
    environment:
      RABBITMQ_DEFAULT_USER: rabbit 
      RABBITMQ_DEFAULT_PASS: rabbit-admin
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    profiles:
      - web 
      - worker