services:
  eventphotographer:
    image: ${DOCKER_REGISTRY-}eventphotographer
    build:
      context: .
      dockerfile: EventPhotographer/Dockerfile

  eventphotographer-worker:
    image: ${DOCKER_REGISTRY-}eventphotographer-worker
    build:
      context: .
      dockerfile: EventPhotographer.Worker/Dockerfile
