<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EventPhotographer.Worker-368f792b-346f-4156-bdb2-b9f5dbc05a1b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CreateCompressedEventFileArchiveConsumer.cs" />
    <Compile Remove="FileWasUploadedMessageConsumer.cs" />
    <Compile Remove="ProcessWhatsAppWebhookConsumer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.25" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Sentry.AspNetCore" Version="6.11.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventPhotographer.UseCases\EventPhotographer.UseCases.csproj" />
    <ProjectReference Include="..\EventPhotographer.Core\EventPhotographer.Core.csproj" />
  </ItemGroup>
</Project>
